# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'user_window_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class Ui_user_window(QtWidgets.QDialog):
    def __init__(self, mywindow_instance):
        super().__init__()
        self.mywindow = mywindow_instance
        self.setupUi(self)

    def setupUi(self, user_window):
        user_window.setObjectName("user_window")
        user_window.resize(561, 532)
        self.photo = QtWidgets.QLabel(user_window)
        self.photo.setGeometry(QtCore.QRect(40, 60, 131, 191))
        self.photo.setText("")
        self.photo.setObjectName("photo")
        self.personal_info = QtWidgets.QLabel(user_window)
        self.personal_info.setGeometry(QtCore.QRect(250, 10, 67, 17))
        self.personal_info.setObjectName("personal_info")
        self.username = QtWidgets.QLabel(user_window)
        self.username.setGeometry(QtCore.QRect(190, 60, 67, 17))
        self.username.setObjectName("username")
        self.tel = QtWidgets.QLabel(user_window)
        self.tel.setGeometry(QtCore.QRect(190, 140, 67, 17))
        self.tel.setObjectName("tel")
        self.email = QtWidgets.QLabel(user_window)
        self.email.setGeometry(QtCore.QRect(190, 220, 67, 17))
        self.email.setObjectName("email")
        self.exitButton = QtWidgets.QPushButton(user_window)
        self.exitButton.setGeometry(QtCore.QRect(390, 310, 89, 25))
        self.exitButton.setObjectName("exitButton")
        self.get_username = QtWidgets.QLabel(user_window)
        self.get_username.setGeometry(QtCore.QRect(270, 60, 111, 21))
        self.get_username.setObjectName("get_name")
        self.get_tel = QtWidgets.QLabel(user_window)
        self.get_tel.setGeometry(QtCore.QRect(270, 140, 111, 21))
        self.get_tel.setObjectName("get_tel")
        self.get_email = QtWidgets.QLabel(user_window)
        self.get_email.setGeometry(QtCore.QRect(270, 220, 111, 21))
        self.get_email.setObjectName("get_email")

        self.exitButton.clicked.connect(self.close)

        self.retranslateUi(user_window)
        QtCore.QMetaObject.connectSlotsByName(user_window)

    def retranslateUi(self, user_window):
        _translate = QtCore.QCoreApplication.translate
        username, tel, email = self.mywindow.match_info()
        user_window.setWindowTitle(_translate("user_window", "user"))
        self.personal_info.setText(_translate("user_window", "个人信息"))
        self.username.setText(_translate("user_window", "姓名"))
        self.tel.setText(_translate("user_window", "电话"))
        self.email.setText(_translate("user_window", "邮箱"))
        self.exitButton.setText(_translate("user_window", "关闭"))
        self.get_username.setText(_translate("user_window", username))
        self.get_tel.setText(_translate("user_window", tel))
        self.get_email.setText(_translate("user_window", email))

        photo_path = os.path.join("user_photo", f"{username}.jpg")
        pixmap = QPixmap(photo_path)
        self.photo.setPixmap(pixmap)
        self.photo.setScaledContents(True)



