# 文件名和筛选条件
AllRun_file: '按日期查询run信息，包括平均数，_1Kb_Num_2Kb_Num_2024_01_19.csv'
keyword_FileName: 'Y000'
keyword_NP: ['L617', 'L844']
keyword_columns: ['FileName', 'NP', 'total_avarage_identity', 'total_sub_len', 'subs_more_than_70_pr', 'subs_more_than_75_pr', 'subs_more_than_78_pr', 'subs_more_than_80_pr', 'subs_more_than_83_pr', 'subs_more_than_85_pr', 'total_reads_len', 'valid_reads_num', 'invalid_reads_num', 'total_matched_reads_num', 'total_valid_reads_len', 'total_valid_reads_coverage', 'global_min_len', 'global_max_len', 'global_median_len', 'global_mean_len', 'average_linker_speed', 'average_basecall_lifetime']

# 分析文件
run_file_1: ['L617', 'DPN2674-E-Coli-PN-L617-N042-N101-6Plinker-十烷-60min.csv']
run_file_2: ['L844', 'DPN2675-E-Coli-PN-L844-N042-N101-6Plinker-交联磷脂-60min.csv']

# 分析组合
group_1:
group_2:
group_3:
group_4:

# 分析条件
coverage: '80%'
read_len: '1K'
LT: '30min'

# 错误类型分析-对照实验
compare_60min: ['Run_file_2', 'Run_file_4']
compare_30min: ['Run_file_1', 'Run_file_3']